SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[jcm_vw_JobSummaryVariations]
AS
SELECT     dbo.jcm_JobVariations.[Job ID], dbo.jcm_JobVariations.[Var No], dbo.jcm_JobVariations.[Var Date], dbo.jcm_JobVariations.[Var Description], 
                      dbo.jcm_JobVariations.[Var Comment], dbo.jcm_JobVariations.[est A], dbo.jcm_JobVariations.[est B], dbo.jcm_JobVariations.[est D], 
                      dbo.jcm_JobVariations.[est E], dbo.jcm_JobVariations.[est L], dbo.jcm_JobVariations.[est P], dbo.jcm_JobVariations.[est S], 
                      dbo.jcm_JobVariations.[est T], dbo.jcm_JobVariations.[est W], dbo.jcm_JobVariations.[est Prog], dbo.jcm_JobVariations.[est Doc], 
                      dbo.jcm_JobVariations.[est Warr], dbo.jcm_JobVariations.[est Design], dbo.jcm_JobVariations.[est Sup], dbo.jcm_JobVariations.[est Quoted$], 
                      dbo.jcm_JobVariations.[est Materials$], dbo.jcm_JobVariations.[est Labour$], dbo.jcm_JobVariations.[est Sundry$], 
                      dbo.jcm_JobVariations.[est Labels$], dbo.jcm_JobVariations.[est Freight$], dbo.jcm_JobVariations.[est Contractor$], dbo.jcm_JobVariations.[Quote No], 
                      dbo.jcm_JobVariations.Customer, dbo.jcm_JobVariations.[Customer ABN], dbo.jcm_JobVariations.[Order No], dbo.jcm_JobVariations.DrawingsReq, 
                      dbo.jcm_JobVariations.[Drawings By], dbo.jcm_JobVariations.[Deliver By], dbo.jcm_JobVariations.DeliverToSiteBy, 
                      dbo.jcm_JobVariations.LastModified, dbo.jcm_JobVariations.OrderAckLetter, dbo.jcm_JobVariations.FileTypeReq, dbo.jcm_JobVariations.IOMReq, 
                      dbo.jcm_JobVariations.EstablishedAcct, dbo.jcm_JobVariations.CreditChecked, dbo.jcm_JobVariations.CreditAppReq, 
                      dbo.jcm_JobVariations.SpecialInsDelv, dbo.jcm_JobVariations.ProfIndemnityHrs, dbo.jcm_JobVariations.ProfIndemnityRate, 
                      dbo.jcm_JobVariations.ProfIndemnityMaterial, dbo.jcm_JobVariations.SiteWorksHrs, dbo.jcm_JobVariations.SiteWorksRate, 
                      dbo.jcm_JobVariations.SiteWorksMaterial, dbo.jcm_JobVariations.MANSalesNo, dbo.jcm_JobVariations.MANAssbHrs, 
                      dbo.jcm_JobVariations.MANAssbRate, dbo.jcm_JobVariations.MANBusbarHrs, dbo.jcm_JobVariations.MANBusbarRate, 
                      dbo.jcm_JobVariations.MANLayoutHrs, dbo.jcm_JobVariations.MANLayoutRate, dbo.jcm_JobVariations.MANEscutHrs, 
                      dbo.jcm_JobVariations.MANEscutRate, dbo.jcm_JobVariations.MANPrepHrs, dbo.jcm_JobVariations.MANPrepRate, 
                      dbo.jcm_JobVariations.MANWiringHrs, dbo.jcm_JobVariations.MANWiringRate, dbo.jcm_JobVariations.MANSiteWorkHrs, 
                      dbo.jcm_JobVariations.MANSiteWorkRate, dbo.jcm_JobVariations.MANInstallationHrs, dbo.jcm_JobVariations.MANInstallationRate, 
                      dbo.jcm_JobVariations.MANTestingHrs, dbo.jcm_JobVariations.MANTestingRate, dbo.jcm_JobVariations.MANCommissioningHrs, 
                      dbo.jcm_JobVariations.MANCommissioningRate, dbo.jcm_JobVariations.MANProgrammingHrs, dbo.jcm_JobVariations.MANProgrammingRate, 
                      dbo.jcm_JobVariations.MANWarrantyHrs, dbo.jcm_JobVariations.MANWarrantyRate, dbo.jcm_JobVariations.MANDraftingHrs, 
                      dbo.jcm_JobVariations.MANDraftingRate, dbo.jcm_JobVariations.MANDesignHrs, dbo.jcm_JobVariations.MANDesignRate, 
                      dbo.jcm_JobVariations.MANSupervisionHrs, dbo.jcm_JobVariations.MANSupervisionRate, dbo.jcm_JobVariations.MANDocumentationHrs, 
                      dbo.jcm_JobVariations.MANDocumentationRate, dbo.jcm_JobVariations.ENGSalesNo, dbo.jcm_JobVariations.ENGAssbHrs, 
                      dbo.jcm_JobVariations.ENGAssbRate, dbo.jcm_JobVariations.ENGBusbarHrs, dbo.jcm_JobVariations.ENGBusbarRate, 
                      dbo.jcm_JobVariations.ENGLayoutHrs, dbo.jcm_JobVariations.ENGLayoutRate, dbo.jcm_JobVariations.ENGEscutHrs, 
                      dbo.jcm_JobVariations.ENGEscutRate, dbo.jcm_JobVariations.ENGPrepHrs, dbo.jcm_JobVariations.ENGPrepRate, 
                      dbo.jcm_JobVariations.ENGWiringHrs, dbo.jcm_JobVariations.ENGWiringRate, dbo.jcm_JobVariations.ENGSiteWorkHrs, 
                      dbo.jcm_JobVariations.ENGSiteWorkRate, dbo.jcm_JobVariations.ENGInstallationHrs, dbo.jcm_JobVariations.ENGInstallationRate, 
                      dbo.jcm_JobVariations.ENGTestingHrs, dbo.jcm_JobVariations.ENGTestingRate, dbo.jcm_JobVariations.ENGCommissioningHrs, 
                      dbo.jcm_JobVariations.ENGCommissioningRate, dbo.jcm_JobVariations.ENGProgrammingHrs, dbo.jcm_JobVariations.ENGProgrammingRate, 
                      dbo.jcm_JobVariations.ENGWarrantyHrs, dbo.jcm_JobVariations.ENGWarrantyRate, dbo.jcm_JobVariations.ENGDraftingHrs, 
                      dbo.jcm_JobVariations.ENGDraftingRate, dbo.jcm_JobVariations.ENGDesignHrs, dbo.jcm_JobVariations.ENGDesignRate, 
                      dbo.jcm_JobVariations.ENGSupervisionHrs, dbo.jcm_JobVariations.ENGSupervisionRate, dbo.jcm_JobVariations.ENGDocumentationHrs, 
                      dbo.jcm_JobVariations.ENGDocumentationRate, dbo.jcm_JobVariations.incomplete, dbo.jcm_JobVariations.commContact, 
                      dbo.jcm_JobVariations.techContact, dbo.jcm_JobVariations.phoneNo, dbo.jcm_JobVariations.faxNo, dbo.jcm_JobVariations.mobileNo, 
                      dbo.jcm_JobVariations.QSLevel, dbo.jcm_JobVariations.projectDividers, dbo.jcm_JobVariations.suppliersList, dbo.jcm_JobVariations.acctsAuthorised, 
                      dbo.jcm_JobVariations.acctsAuthDate, dbo.jcm_JobVariations.tonyAuthorised, dbo.jcm_JobVariations.tonyAuthDate, 
                      dbo.jcm_JobVariations.jobAuthorised, dbo.jcm_JobVariations.jobAuthDate, dbo.jcm_JobVariations.MANTotalExcGST, 
                      dbo.jcm_JobVariations.MANCogsMat, dbo.jcm_JobVariations.MANSundry, dbo.jcm_JobVariations.MANLabels, dbo.jcm_JobVariations.MANFreight, 
                      dbo.jcm_JobVariations.MANSubCon, dbo.jcm_JobVariations.ENGTotalExcGST, dbo.jcm_JobVariations.ENGCogsMat, 
                      dbo.jcm_JobVariations.ENGSundry, dbo.jcm_JobVariations.ENGLabels, dbo.jcm_JobVariations.ENGFreight, dbo.jcm_JobVariations.ENGSubCon, 
                      dbo.jcm_JobVariations.AuditCreatedBy, dbo.jcm_JobVariations.AuditCreated, dbo.jcm_JobVariations.AuditUpdatedBy, 
                      dbo.jcm_JobVariations.AuditUpdated, dbo.jcm_JobVariations.originator, dbo.jcm_JobVariations.[entered by], dbo.jcm_JobVariations.startupSheet, 
		      dbo.jcm_JobVariations.AssignedTo, dbo.jcm_JobVariations.SUBCONTRACTORUSED,
		      dbo.jcm_JobSummary.[Job ID] AS JobID, dbo.jcm_JobSummary.[Job No], dbo.jcm_JobSummary.[Job Description], 
                      dbo.jcm_JobSummary.[Job Location], dbo.jcm_JobSummary.[act Mat&Sund&Lab$], dbo.jcm_JobSummary.[act Labour$], 
                      dbo.jcm_JobSummary.Invoiced, dbo.jcm_JobSummary.[Under/Over Date], dbo.jcm_JobSummary.[On Hold], dbo.jcm_JobSummary.[Cost Plus], 
                      dbo.jcm_JobSummary.[Display Eng Prod], dbo.jcm_JobSummary.[Display Sw Prod], dbo.jcm_JobSummary.[SSS Job], 
                      dbo.jcm_JobSummary.[R&D Job], dbo.jcm_JobSummary.Deleted, dbo.jcm_JobSummary.[Last Modified], dbo.jcm_JobSummary.Archive, 
                      dbo.jcm_JobSummary.ProjectFilePath, dbo.jcm_JobSummary.AuditCreatedBy AS jobSumCreatedBy, 
                      dbo.jcm_JobSummary.AuditCreated AS jobSumCreated, dbo.jcm_JobSummary.AuditUpdatedBy AS jobSumUpdatedBy, 
                      dbo.jcm_JobSummary.AuditUpdated AS jobSumUpdated, dbo.jcm_JobVariations.[Var Date] AS [Date Started]
FROM         dbo.jcm_JobSummary INNER JOIN
                      dbo.jcm_JobVariations ON dbo.jcm_JobSummary.[Job ID] = dbo.jcm_JobVariations.[Job ID]


GO