CREATE TABLE [dbo].[ipl_tblCollectedImports] (
  [BrandID] [int] NOT NULL,
  [Brand] [nvarchar](50) NULL,
  [SupplierPartCode] [nvarchar](50) NOT NULL,
  [SupplierBarcode] [char](50) NULL,
  [SupplierDescription] [nvarchar](255) NULL,
  [SupplierDescription2] [nvarchar](255) NULL,
  [SupplierProductGroup] [nvarchar](50) NULL,
  [SupplierCategory] [nvarchar](50) NULL,
  [SupplierUOM] [nvarchar](6) NULL,
  [StandardPack] [nvarchar](50) NULL,
  [TradePrice] [money] NULL,
  [StdDiscount] [real] NULL,
  [OEMPrice] [money] NULL,
  [WebPrice] [money] NULL,
  [Category1] [int] NULL,
  [Category2] [int] NULL,
  [Category3] [int] NULL,
  [QMCategory] [int] NULL,
  [LastUpdated] [smalldatetime] NULL,
  [Add?] [bit] NOT NULL CONSTRAINT [DF_ipl_tblCollectedImports_Add?] DEFAULT (0),
  [New?] [bit] NOT NULL CONSTRAINT [DF_ipl_tblCollectedImports_New?] DEFAULT (0),
  [Obsolete?] [bit] NOT NULL CONSTRAINT [DF_ipl_tblCollectedImports_Obsolete?] DEFAULT (0),
  [MatchField] [nvarchar](50) NULL,
  [Match] [nvarchar](50) NULL,
  [Conversion] [nvarchar](50) NULL CONSTRAINT [DF_ipl_tblCollectedImports_Conversion] DEFAULT (1),
  [WholesaleDiscount] [real] NULL,
  [SupplierDiscountCode] [nvarchar](50) NULL,
  [QuoteNetCost] [money] NULL,
  [WholesaleCost] [money] NULL,
  [CostPriceLPP] [money] NULL,
  [CostPriceLPPNew] [money] NULL,
  [QuoteDefaultDiscount] [real] NULL,
  CONSTRAINT [PK_ipl_tblCollectedImports] PRIMARY KEY CLUSTERED ([BrandID], [SupplierPartCode])
)
ON [PRIMARY]
GO