CREATE TABLE [dbo].[jcm_CustInvoiceNotification] (
  [CIN_ID] [int] IDENTITY,
  [JobID] [int] NOT NULL,
  [DescProblem] [text] NULL,
  [DescSolution] [text] NULL,
  [MU_GoodsIssued] [text] NULL,
  [MU_SupplierOrders] [text] NULL,
  [MU_EngineeringSpares] [text] NULL,
  [HoursCharged] [real] NULL,
  [RequestedBy] [nvarchar](255) NULL,
  [OnSite] [smallint] NULL,
  [AfterHours] [smallint] NULL,
  [DateEntered] [datetime] NOT NULL,
  [User] [nvarchar](255) NOT NULL,
  [SpecialAirfreight] [smallint] NULL,
  [SpecialAirfreightCarrier] [nvarchar](255) NULL,
  [MU_Leftovers] [text] NULL,
  [StaffOnJob] [nvarchar](255) NULL,
  [SpecialComments] [text] NULL,
  [DateCompleted] [datetime] NULL,
  [boolManualCIN] [smallint] NULL,
  [boolArchive] [smallint] NULL,
  [QuotedPrice] [real] NULL,
  [Order No] [nvarchar](20) NULL,
  [VarNo] [int] NULL,
  [KMCharged] [real] NULL,
  [LabourRate] [nvarchar](255) NULL,
  [boolJSEA] [smallint] NULL,
  [boolSTSR] [smallint] NULL,
  [MU_boolSupplierOrders] [smallint] NULL,
  [FreightCost] [real] NULL,
  [MU_boolEngineeringSpares] [smallint] NULL,
  [MU_boolLeftovers] [smallint] NULL,
  [MU_boolGoodsIssued] [smallint] NULL,
  CONSTRAINT [PK_jcm_CustomerInvoiceNotification] PRIMARY KEY CLUSTERED ([CIN_ID])
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO