CREATE TABLE [dbo].[ord_tblJobSheetPartsAudit] (
  [audit_id] [int] IDENTITY,
  [AuditUser] [nvarchar](50) NULL CONSTRAINT [DF_ord_tblJobSheetPartsAudit_AuditUser] DEFAULT (suser_sname()),
  [AuditDate] [datetime] NULL CONSTRAINT [DF_ord_tblJobSheetPartsAudit_AuditDate] DEFAULT (getdate()),
  [AuditOperation] [nvarchar](50) NULL CONSTRAINT [DF_ord_tblJobSheetPartsAudit_AuditOperation] DEFAULT (N'INSERT'),
  [jspartsid] [int] NULL,
  [job_sheet_id] [int] NULL,
  [order_no] [nvarchar](30) NULL,
  [order?] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_audit_order?] DEFAULT (0),
  [supplier] [nvarchar](50) NULL,
  [brand] [nvarchar](30) NULL,
  [cat_no] [nvarchar](50) NULL,
  [description] [nvarchar](100) NULL,
  [secondary_part_code] [nvarchar](25) NULL,
  [comment] [nvarchar](100) NULL,
  [price] [money] NULL,
  [disc] [real] NULL,
  [qty] [real] NULL,
  [other_qty] [real] NULL,
  [ordered] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_audit_ordered] DEFAULT (0),
  [proposed] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_audit_proposed] DEFAULT (0),
  [order date] [smalldatetime] NULL,
  [OLDjspartsid] [int] NULL,
  [OLDjob_sheet_id] [int] NULL,
  [OLDorder_no] [nvarchar](30) NULL,
  [OLDorder?] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_audit_order?1] DEFAULT (0),
  [OLDsupplier] [nvarchar](50) NULL,
  [OLDbrand] [nvarchar](30) NULL,
  [OLDcat_no] [nvarchar](50) NULL,
  [OLDdescription] [nvarchar](100) NULL,
  [OLDsecondary_part_code] [nvarchar](25) NULL,
  [OLDcomment] [nvarchar](100) NULL,
  [OLDprice] [money] NULL,
  [OLDdisc] [real] NULL,
  [OLDqty] [real] NULL,
  [OLDother_qty] [real] NULL,
  [OLDordered] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_audit_ordered1] DEFAULT (0),
  [OLDproposed] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_audit_proposed1] DEFAULT (0),
  [OLDorder date] [smalldatetime] NULL,
  CONSTRAINT [PK_job_sheet_parts_audit] PRIMARY KEY CLUSTERED ([audit_id])
)
ON [PRIMARY]
GO