CREATE TABLE [dbo].[MODULE_SUMMARY_DEFAULT_Q] (
  [freight] [money] NOT NULL CONSTRAINT [DF_MODULE_SUMMARY_DEFAULT_Q_freight] DEFAULT (0),
  [sundry] [money] NOT NULL CONSTRAINT [DF_MODULE_SUMMARY_DEFAULT_Q_sundry] DEFAULT (0),
  CONSTRAINT [PK_MODULE_SUMMARY_DEFAULT_Q] PRIMARY KEY CLUSTERED ([freight], [sundry])
)
ON [PRIMARY]
GO