CREATE TABLE [dbo].[jcm_tblJobVariationsAudit] (
  [AuditID] [int] IDENTITY,
  [AuditUser] [nvarchar](50) NULL,
  [AuditDate] [datetime] NULL,
  [AuditOperation] [nvarchar](50) NULL,
  [Job ID] [int] NULL,
  [Var No] [int] NULL,
  [Var Date] [smalldatetime] NULL,
  [Var Description] [nvarchar](255) NULL,
  [Var Comment] [nvarchar](1000) NULL,
  [est A] [real] NULL,
  [est B] [real] NULL,
  [est D] [real] NULL,
  [est E] [real] NULL,
  [est L] [real] NULL,
  [est P] [real] NULL,
  [est S] [real] NULL,
  [est T] [real] NULL,
  [est W] [real] NULL,
  [est Prog] [real] NULL,
  [est Doc] [real] NULL,
  [est Warr] [real] NULL,
  [est Design] [real] NULL,
  [est Sup] [real] NULL,
  [est Quoted$] [money] NULL,
  [est Materials$] [money] NULL,
  [est Labour$] [money] NULL,
  [est Sundry$] [money] NULL,
  [est Labels$] [money] NULL,
  [est Freight$] [money] NULL,
  [est Contractor$] [money] NULL,
  [VarQuoteNo] [nvarchar](15) NULL,
  [VarCustomer] [nvarchar](50) NULL,
  [CustomerABN] [nvarchar](20) NULL,
  [OrderNo] [nvarchar](20) NULL,
  [DrawingsReq] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_DrawingsReq] DEFAULT (0),
  [DrawingsBy] [smalldatetime] NULL,
  [DeliverBy] [smalldatetime] NULL,
  [DeliverToSiteBy] [nvarchar](50) NULL,
  [LastModified] [smalldatetime] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_LastModified] DEFAULT (getdate()),
  [OrderAckLetter] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OrderAckLetter] DEFAULT (0),
  [FileTypeReq] [nvarchar](50) NULL,
  [IOMReq] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_IOMReq] DEFAULT (0),
  [EstablishedAcct] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_EstablishedAcct] DEFAULT (0),
  [CreditChecked] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_CreditChecked] DEFAULT (0),
  [CreditAppReq] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_CreditAppReq] DEFAULT (0),
  [SpecialInsDelv] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_SpecialInsDelv] DEFAULT (0),
  [ProfIndemnityHrs] [int] NULL,
  [ProfIndemnityRate] [money] NULL,
  [ProfIndemnityMaterial] [money] NULL,
  [SiteWorksHrs] [int] NULL,
  [SiteWorksRate] [money] NULL,
  [SiteWorksMaterial] [money] NULL,
  [MANSalesNo] [nvarchar](10) NULL,
  [MANAssbHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANAssbHrs] DEFAULT (0),
  [MANAssbRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANAssbRate] DEFAULT (0),
  [MANBusbarHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANBusbarHrs] DEFAULT (0),
  [MANBusbarRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANBusbarRate] DEFAULT (0),
  [MANLayoutHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANLayoutHrs] DEFAULT (0),
  [MANLayoutRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANLayoutRate] DEFAULT (0),
  [MANEscutHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANEscutHrs] DEFAULT (0),
  [MANEscutRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANEscutRate] DEFAULT (0),
  [MANPrepHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANPrepHrs] DEFAULT (0),
  [MANPrepRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANPrepRate] DEFAULT (0),
  [MANWiringHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANWiringHrs] DEFAULT (0),
  [MANWiringRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANWiringRate] DEFAULT (0),
  [MANSiteWorkHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANSiteWorkHrs] DEFAULT (0),
  [MANSiteWorkRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANSiteWorkRate] DEFAULT (0),
  [MANInstallationHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANInstallationHrs] DEFAULT (0),
  [MANInstallationRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANInstallationRate] DEFAULT (0),
  [MANTestingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANTestingHrs] DEFAULT (0),
  [MANTestingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANTestingRate] DEFAULT (0),
  [MANCommissioningHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANCommissioningHrs] DEFAULT (0),
  [MANCommissioningRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANCommissioningRate] DEFAULT (0),
  [MANProgrammingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANProgrammingHrs] DEFAULT (0),
  [MANProgrammingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANProgrammingRate] DEFAULT (0),
  [MANWarrantyHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANWarrantyHrs] DEFAULT (0),
  [MANWarrantyRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANWarrantyRate] DEFAULT (0),
  [MANDraftingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANDraftingHrs] DEFAULT (0),
  [MANDraftingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANDraftingRate] DEFAULT (0),
  [MANDesignHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANDesignHrs] DEFAULT (0),
  [MANDesignRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANDesignRate] DEFAULT (0),
  [MANSupervisionHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANSupervisionHrs] DEFAULT (0),
  [MANSupervisionRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANSupervisionRate] DEFAULT (0),
  [MANDocumentationHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANDocumentationHrs] DEFAULT (0),
  [MANDocumentationRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_MANDocumentationRate] DEFAULT (0),
  [ENGSalesNo] [nvarchar](10) NULL,
  [ENGAssbHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGAssbHrs] DEFAULT (0),
  [ENGAssbRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGAssbRate] DEFAULT (0),
  [ENGBusbarHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGBusbarHrs] DEFAULT (0),
  [ENGBusbarRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGBusbarRate] DEFAULT (0),
  [ENGLayoutHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGLayoutHrs] DEFAULT (0),
  [ENGLayoutRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGLayoutRate] DEFAULT (0),
  [ENGEscutHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGEscutHrs] DEFAULT (0),
  [ENGEscutRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGEscutRate] DEFAULT (0),
  [ENGPrepHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGPrepHrs] DEFAULT (0),
  [ENGPrepRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGPrepRate] DEFAULT (0),
  [ENGWiringHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGWiringHrs] DEFAULT (0),
  [ENGWiringRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGWiringRate] DEFAULT (0),
  [ENGSiteWorkHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGSiteWorkHrs] DEFAULT (0),
  [ENGSiteWorkRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGSiteWorkRate] DEFAULT (0),
  [ENGInstallationHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGInstallationHrs] DEFAULT (0),
  [ENGInstallationRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGInstallationRate] DEFAULT (0),
  [ENGTestingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGTestingHrs] DEFAULT (0),
  [ENGTestingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGTestingRate] DEFAULT (0),
  [ENGCommissioningHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGCommissioningHrs] DEFAULT (0),
  [ENGCommissioningRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGCommissioningRate] DEFAULT (0),
  [ENGProgrammingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGProgrammingHrs] DEFAULT (0),
  [ENGProgrammingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGProgrammingRate] DEFAULT (0),
  [ENGWarrantyHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGWarrantyHrs] DEFAULT (0),
  [ENGWarrantyRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGWarrantyRate] DEFAULT (0),
  [ENGDraftingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGDraftingHrs] DEFAULT (0),
  [ENGDraftingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGDraftingRate] DEFAULT (0),
  [ENGDesignHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGDesignHrs] DEFAULT (0),
  [ENGDesignRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGDesignRate] DEFAULT (0),
  [ENGSupervisionHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGSupervisionHrs] DEFAULT (0),
  [ENGSupervisionRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGSupervisionRate] DEFAULT (0),
  [ENGDocumentationHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGDocumentationHrs] DEFAULT (0),
  [ENGDocumentationRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_ENGDocumentationRate] DEFAULT (0),
  [incomplete] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_incomplete] DEFAULT (0),
  [commContact] [nvarchar](50) NULL,
  [techContact] [nvarchar](50) NULL,
  [phoneNo] [nvarchar](50) NULL,
  [faxNo] [nvarchar](50) NULL,
  [mobileNo] [nvarchar](50) NULL,
  [QSLevel] [nvarchar](1) NULL,
  [projectDividers] [nvarchar](50) NULL,
  [suppliersList] [nvarchar](50) NULL,
  [acctsAuthorised] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_acctsAuthorised] DEFAULT (0),
  [acctsAuthDate] [datetime] NULL,
  [tonyAuthorised] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_tonyAuthorised] DEFAULT (0),
  [tonyAuthDate] [datetime] NULL,
  [jobAuthorised] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_jobAuthorised] DEFAULT (0),
  [jobAuthDate] [datetime] NULL,
  [MANTotalExcGST] [money] NULL,
  [MANCogsMat] [money] NULL,
  [MANSundry] [money] NULL,
  [MANLabels] [money] NULL,
  [MANFreight] [money] NULL,
  [MANSubCon] [money] NULL,
  [ENGTotalExcGST] [money] NULL,
  [ENGCogsMat] [money] NULL,
  [ENGSundry] [money] NULL,
  [ENGLabels] [money] NULL,
  [ENGFreight] [money] NULL,
  [ENGSubCon] [money] NULL,
  [originator] [nvarchar](50) NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_originator] DEFAULT (suser_sname()),
  [Entered By] [nvarchar](5) NULL,
  [Quote No] [nvarchar](15) NULL,
  [Customer] [nvarchar](50) NULL,
  [Customer ABN] [nvarchar](20) NULL,
  [Account] [nvarchar](20) NULL,
  [Sales No] [nvarchar](10) NULL,
  [Order No] [nvarchar](20) NULL,
  [Drawings By] [smalldatetime] NULL,
  [Deliver By] [smalldatetime] NULL,
  [OLDVar No] [int] NULL,
  [OLDVar Date] [smalldatetime] NULL,
  [OLDVar Description] [nvarchar](255) NULL,
  [OLDVar Comment] [nvarchar](255) NULL,
  [OLDest A] [real] NULL,
  [OLDest B] [real] NULL,
  [OLDest D] [real] NULL,
  [OLDest E] [real] NULL,
  [OLDest L] [real] NULL,
  [OLDest P] [real] NULL,
  [OLDest S] [real] NULL,
  [OLDest T] [real] NULL,
  [OLDest W] [real] NULL,
  [OLDest Prog] [real] NULL,
  [OLDest Doc] [real] NULL,
  [OLDest Warr] [real] NULL,
  [OLDest Design] [real] NULL,
  [OLDest Sup] [real] NULL,
  [OLDest Quoted$] [money] NULL,
  [OLDest Materials$] [money] NULL,
  [OLDest Labour$] [money] NULL,
  [OLDest Sundry$] [money] NULL,
  [OLDest Labels$] [money] NULL,
  [OLDest Freight$] [money] NULL,
  [OLDest Contractor$] [money] NULL,
  [OLDVarQuoteNo] [nvarchar](15) NULL,
  [OLDVarCustomer] [nvarchar](50) NULL,
  [OLDCustomerABN] [nvarchar](20) NULL,
  [OLDOrderNo] [nvarchar](20) NULL,
  [OLDDrawingsReq] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDDrawingsReq] DEFAULT (0),
  [OLDDrawingsBy] [smalldatetime] NULL,
  [OLDDeliverBy] [smalldatetime] NULL,
  [OLDDeliverToSiteBy] [nvarchar](50) NULL,
  [OLDLastModified] [smalldatetime] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDLastModified] DEFAULT (getdate()),
  [OLDOrderAckLetter] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDOrderAckLetter] DEFAULT (0),
  [OLDFileTypeReq] [nvarchar](50) NULL,
  [OLDIOMReq] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDIOMReq] DEFAULT (0),
  [OLDEstablishedAcct] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDEstablishedAcct] DEFAULT (0),
  [OLDCreditChecked] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDCreditChecked] DEFAULT (0),
  [OLDCreditAppReq] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDCreditAppReq] DEFAULT (0),
  [OLDSpecialInsDelv] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDSpecialInsDelv] DEFAULT (0),
  [OLDProfIndemnityHrs] [int] NULL,
  [OLDProfIndemnityRate] [money] NULL,
  [OLDProfIndemnityMaterial] [money] NULL,
  [OLDSiteWorksHrs] [int] NULL,
  [OLDSiteWorksRate] [money] NULL,
  [OLDSiteWorksMaterial] [money] NULL,
  [OLDMANSalesNo] [nvarchar](10) NULL,
  [OLDMANAssbHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANAssbHrs] DEFAULT (0),
  [OLDMANAssbRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANAssbRate] DEFAULT (0),
  [OLDMANBusbarHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANBusbarHrs] DEFAULT (0),
  [OLDMANBusbarRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANBusbarRate] DEFAULT (0),
  [OLDMANLayoutHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANLayoutHrs] DEFAULT (0),
  [OLDMANLayoutRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANLayoutRate] DEFAULT (0),
  [OLDMANEscutHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANEscutHrs] DEFAULT (0),
  [OLDMANEscutRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANEscutRate] DEFAULT (0),
  [OLDMANPrepHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANPrepHrs] DEFAULT (0),
  [OLDMANPrepRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANPrepRate] DEFAULT (0),
  [OLDMANWiringHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANWiringHrs] DEFAULT (0),
  [OLDMANWiringRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANWiringRate] DEFAULT (0),
  [OLDMANSiteWorkHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANSiteWorkHrs] DEFAULT (0),
  [OLDMANSiteWorkRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANSiteWorkRate] DEFAULT (0),
  [OLDMANInstallationHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANInstallationHrs] DEFAULT (0),
  [OLDMANInstallationRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANInstallationRate] DEFAULT (0),
  [OLDMANTestingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANTestingHrs] DEFAULT (0),
  [OLDMANTestingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANTestingRate] DEFAULT (0),
  [OLDMANCommissioningHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANCommissioningHrs] DEFAULT (0),
  [OLDMANCommissioningRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANCommissioningRate] DEFAULT (0),
  [OLDMANProgrammingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANProgrammingHrs] DEFAULT (0),
  [OLDMANProgrammingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANProgrammingRate] DEFAULT (0),
  [OLDMANWarrantyHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANWarrantyHrs] DEFAULT (0),
  [OLDMANWarrantyRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANWarrantyRate] DEFAULT (0),
  [OLDMANDraftingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANDraftingHrs] DEFAULT (0),
  [OLDMANDraftingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANDraftingRate] DEFAULT (0),
  [OLDMANDesignHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANDesignHrs] DEFAULT (0),
  [OLDMANDesignRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANDesignRate] DEFAULT (0),
  [OLDMANSupervisionHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANSupervisionHrs] DEFAULT (0),
  [OLDMANSupervisionRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDOLDMANSupervisionRate] DEFAULT (0),
  [OLDMANDocumentationHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANDocumentationHrs] DEFAULT (0),
  [OLDMANDocumentationRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDMANDocumentationRate] DEFAULT (0),
  [OLDENGSalesNo] [nvarchar](10) NULL,
  [OLDENGAssbHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGAssbHrs] DEFAULT (0),
  [OLDENGAssbRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGAssbRate] DEFAULT (0),
  [OLDENGBusbarHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGBusbarHrs] DEFAULT (0),
  [OLDENGBusbarRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGBusbarRate] DEFAULT (0),
  [OLDENGLayoutHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGLayoutHrs] DEFAULT (0),
  [OLDENGLayoutRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGLayoutRate] DEFAULT (0),
  [OLDENGEscutHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGEscutHrs] DEFAULT (0),
  [OLDENGEscutRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGEscutRate] DEFAULT (0),
  [OLDENGPrepHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGPrepHrs] DEFAULT (0),
  [OLDENGPrepRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGPrepRate] DEFAULT (0),
  [OLDENGWiringHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGWiringHrs] DEFAULT (0),
  [OLDENGWiringRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGWiringRate] DEFAULT (0),
  [OLDENGSiteWorkHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGSiteWorkHrs] DEFAULT (0),
  [OLDENGSiteWorkRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGSiteWorkRate] DEFAULT (0),
  [OLDENGInstallationHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGInstallationHrs] DEFAULT (0),
  [OLDENGInstallationRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGInstallationRate] DEFAULT (0),
  [OLDENGTestingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGTestingHrs] DEFAULT (0),
  [OLDENGTestingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGTestingRate] DEFAULT (0),
  [OLDENGCommissioningHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGCommissioningHrs] DEFAULT (0),
  [OLDENGCommissioningRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGCommissioningRate] DEFAULT (0),
  [OLDENGProgrammingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGProgrammingHrs] DEFAULT (0),
  [OLDENGProgrammingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGProgrammingRate] DEFAULT (0),
  [OLDENGWarrantyHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGWarrantyHrs] DEFAULT (0),
  [OLDENGWarrantyRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGWarrantyRate] DEFAULT (0),
  [OLDENGDraftingHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGDraftingHrs] DEFAULT (0),
  [OLDENGDraftingRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGDraftingRate] DEFAULT (0),
  [OLDENGDesignHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGDesignHrs] DEFAULT (0),
  [OLDENGDesignRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGDesignRate] DEFAULT (0),
  [OLDENGSupervisionHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGSupervisionHrs] DEFAULT (0),
  [OLDENGSupervisionRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGSupervisionRate] DEFAULT (0),
  [OLDENGDocumentationHrs] [real] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGDocumentationHrs] DEFAULT (0),
  [OLDENGDocumentationRate] [money] NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDENGDocumentationRate] DEFAULT (0),
  [OLDincomplete] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDincomplete] DEFAULT (0),
  [OLDcommContact] [nvarchar](50) NULL,
  [OLDtechContact] [nvarchar](50) NULL,
  [OLDphoneNo] [nvarchar](50) NULL,
  [OLDfaxNo] [nvarchar](50) NULL,
  [OLDmobileNo] [nvarchar](50) NULL,
  [OLDQSLevel] [nvarchar](1) NULL,
  [OLDprojectDividers] [nvarchar](50) NULL,
  [OLDsuppliersList] [nvarchar](50) NULL,
  [OLDacctsAuthorised] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDacctsAuthorised] DEFAULT (0),
  [OLDacctsAuthDate] [datetime] NULL,
  [OLDtonyAuthorised] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDtonyAuthorised] DEFAULT (0),
  [OLDtonyAuthDate] [datetime] NULL,
  [OLDjobAuthorised] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDjobAuthorised] DEFAULT (0),
  [OLDjobAuthDate] [datetime] NULL,
  [OLDMANTotalExcGST] [money] NULL,
  [OLDMANCogsMat] [money] NULL,
  [OLDMANSundry] [money] NULL,
  [OLDMANLabels] [money] NULL,
  [OLDMANFreight] [money] NULL,
  [OLDMANSubCon] [money] NULL,
  [OLDENGTotalExcGST] [money] NULL,
  [OLDENGCogsMat] [money] NULL,
  [OLDENGSundry] [money] NULL,
  [OLDENGLabels] [money] NULL,
  [OLDENGFreight] [money] NULL,
  [OLDENGSubCon] [money] NULL,
  [OLDoriginator] [nvarchar](50) NULL CONSTRAINT [DF_jcm_tblJobVariationsAudit_OLDoriginator] DEFAULT (suser_sname()),
  [OLDEntered By] [nvarchar](5) NULL,
  [OLDQuote No] [nvarchar](15) NULL,
  [OLDCustomer] [nvarchar](50) NULL,
  [OLDCustomer ABN] [nvarchar](20) NULL,
  [OLDAccount] [nvarchar](20) NULL,
  [OLDSales No] [nvarchar](10) NULL,
  [OLDOrder No] [nvarchar](20) NULL,
  [OLDDrawings By] [smalldatetime] NULL,
  [OLDDeliver By] [smalldatetime] NULL,
  CONSTRAINT [PK_jcm_tblJobVariationsAudit] PRIMARY KEY CLUSTERED ([AuditID])
)
ON [PRIMARY]
GO