CREATE TABLE [dbo].[jcm_tblJobSummaryAudit] (
  [AuditID] [int] IDENTITY,
  [AuditUser] [nvarchar](50) NULL,
  [AuditDate] [datetime] NULL,
  [AuditOperation] [nvarchar](50) NULL,
  [Job ID] [int] NOT NULL,
  [Job No] [nvarchar](16) NULL,
  [Job Description] [nvarchar](255) NULL,
  [Job Location] [nvarchar](2) NULL,
  [Entered By] [nvarchar](5) NULL,
  [Quote No] [nvarchar](15) NULL,
  [Customer] [nvarchar](35) NULL,
  [Customer ABN] [nvarchar](20) NULL,
  [Account] [nvarchar](20) NULL,
  [Sales No] [nvarchar](10) NULL,
  [Order No] [nvarchar](20) NULL,
  [Drawings By] [smalldatetime] NULL,
  [Deliver By] [smalldatetime] NULL,
  [act Mat&Sund&Lab$] [money] NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_act Mat&Sund&Lab$] DEFAULT (0),
  [act Labour$] [money] NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_act Labour$] DEFAULT (0),
  [Invoiced] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_Invoiced] DEFAULT (0),
  [Under/Over Date] [smalldatetime] NULL,
  [On Hold] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_On Hold] DEFAULT (0),
  [Cost Plus] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_Cost Plus] DEFAULT (0),
  [Display Eng Prod] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_Display Eng Prod] DEFAULT (0),
  [Display Sw Prod] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_Display Sw Prod] DEFAULT (0),
  [SSS Job] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_SSS Job] DEFAULT (0),
  [Date Started] [smalldatetime] NULL,
  [R&D Job] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_R&D Job] DEFAULT (0),
  [Deleted] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_Deleted] DEFAULT (0),
  [Last Modified] [smalldatetime] NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_Last Modified] DEFAULT (getdate()),
  [Archive] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_Archive] DEFAULT (0),
  [ProjectFilePath] [nvarchar](255) NULL,
  [OLDJob No] [nvarchar](16) NULL,
  [OLDJob Description] [nvarchar](255) NULL,
  [OLDJob Location] [nvarchar](2) NULL,
  [OLDEntered By] [nvarchar](5) NULL,
  [OLDQuote No] [nvarchar](15) NULL,
  [OLDCustomer] [nvarchar](35) NULL,
  [OLDCustomer ABN] [nvarchar](20) NULL,
  [OLDAccount] [nvarchar](20) NULL,
  [OLDSales No] [nvarchar](10) NULL,
  [OLDOrder No] [nvarchar](20) NULL,
  [OLDDrawings By] [smalldatetime] NULL,
  [OLDDeliver By] [smalldatetime] NULL,
  [OLDact Mat&Sund&Lab$] [money] NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDact Mat&Sund&Lab$] DEFAULT (0),
  [OLDact Labour$] [money] NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDact Labour$] DEFAULT (0),
  [OLDInvoiced] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDInvoiced] DEFAULT (0),
  [OLDUnder/Over Date] [smalldatetime] NULL,
  [OLDOn Hold] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDOn Hold] DEFAULT (0),
  [OLDCost Plus] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDCost Plus] DEFAULT (0),
  [OLDDisplay Eng Prod] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDDisplay Eng Prod] DEFAULT (0),
  [OLDDisplay Sw Prod] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDDisplay Sw Prod] DEFAULT (0),
  [OLDSSS Job] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDSSS Job] DEFAULT (0),
  [OLDDate Started] [smalldatetime] NULL,
  [OLDR&D Job] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDR&D Job] DEFAULT (0),
  [OLDDeleted] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDDeleted] DEFAULT (0),
  [OLDLast Modified] [smalldatetime] NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDLast Modified] DEFAULT (getdate()),
  [OLDArchive] [bit] NOT NULL CONSTRAINT [DF_jcm_tblJobSummaryAudit_OLDArchive] DEFAULT (0),
  [OLDProjectFilePath] [nvarchar](255) NULL,
  CONSTRAINT [PK_jcm_tblJobSummaryAudit] PRIMARY KEY CLUSTERED ([AuditID])
)
ON [PRIMARY]
GO