CREATE TABLE [dbo].[jcm_ProjectStartUp] (
  [Job ID] [int] NOT NULL,
  [QuoteNo] [nvarchar](15) NULL,
  [Customer] [nvarchar](35) NULL,
  [CustomerABN] [nvarchar](20) NULL,
  [OrderNo] [nvarchar](20) NULL,
  [DrawingsReq] [bit] NOT NULL CONSTRAINT [DF_jcm_ProjectStartUp_DrawingsReq] DEFAULT (0),
  [DrawingsBy] [smalldatetime] NULL,
  [DeliverBy] [smalldatetime] NULL,
  [DeliverToSiteBy] [nvarchar](50) NULL,
  [LastModified] [smalldatetime] NULL CONSTRAINT [DF_jcm_ProjectStartUp_Last Modified] DEFAULT (getdate()),
  [OrderAckLetter] [bit] NOT NULL CONSTRAINT [DF_jcm_ProjectStartUp_OrderAckLetter] DEFAULT (0),
  [FileTypeReq] [nvarchar](50) NULL,
  [IOMReq] [bit] NOT NULL CONSTRAINT [DF_jcm_ProjectStartUp_IOMReq] DEFAULT (0),
  [EstablishedAcct] [bit] NOT NULL CONSTRAINT [DF_jcm_ProjectStartUp_EstablishedAcct] DEFAULT (0),
  [CreditChecked] [bit] NOT NULL CONSTRAINT [DF_jcm_ProjectStartUp_CreditChecked] DEFAULT (0),
  [CreditAppReq] [bit] NOT NULL CONSTRAINT [DF_jcm_ProjectStartUp_CreditAppReq] DEFAULT (0),
  [SpecialInsDelv] [bit] NOT NULL CONSTRAINT [DF_jcm_ProjectStartUp_SpecialInsDelv] DEFAULT (0),
  [ProfIndemnityHrs] [int] NULL,
  [ProfIndemnityRate] [money] NULL,
  [ProfIndemnityMaterial] [money] NULL,
  [SiteWorksHrs] [int] NULL,
  [SiteWorksRate] [money] NULL,
  [SiteWorksMaterial] [money] NULL,
  [MANSalesNo] [nvarchar](10) NULL,
  [MANAssbHrs] [char](10) NULL,
  [txtMANAssbRate] [char](10) NULL,
  [MANBusbarHrs] [char](10) NULL,
  [MANBusbarRate] [char](10) NULL,
  [MANLayoutHrs] [char](10) NULL,
  [MANLayoutRate] [char](10) NULL,
  [MANEscutHrs] [char](10) NULL,
  [MANEscutRate] [char](10) NULL,
  [MANPrepHrs] [char](10) NULL,
  [MANPrepRate] [char](10) NULL,
  [MANWiringHrs] [char](10) NULL,
  [MANWiringRate] [char](10) NULL,
  [MANSiteWorkHrs] [char](10) NULL,
  [MANSiteWorkRate] [char](10) NULL,
  [MANInstallationHrs] [char](10) NULL,
  [MANInstallationRate] [char](10) NULL,
  [MANTestingHrs] [char](10) NULL,
  [MANTestingRate] [char](10) NULL,
  [MANCommissioningHrs] [char](10) NULL
)
ON [PRIMARY]
GO