CREATE TABLE [dbo].[ord_tblOrdersAudit] (
  [auditID] [int] IDENTITY,
  [AuditUser] [nvarchar](50) NULL CONSTRAINT [DF_ord_tblOrdersAudit_AuditUser_1] DEFAULT (suser_sname()),
  [AuditDate] [datetime] NULL CONSTRAINT [DF_ord_tblOrdersAudit_AuditDate_1] DEFAULT (getdate()),
  [AuditOperation] [nvarchar](50) NULL CONSTRAINT [DF_ord_tblOrdersAudit_AuditOperation_1] DEFAULT (N'INSERT'),
  [orderNo] [nvarchar](30) NULL,
  [supplier] [nvarchar](50) NULL,
  [supplierFax] [varchar](15) NULL,
  [supplierPhone] [varchar](15) NULL,
  [supplierContact] [varchar](50) NULL,
  [orderNote] [varchar](1000) NULL,
  [orderDate] [smalldatetime] NULL,
  [despatchDateReq] [smalldatetime] NULL,
  [service] [nvarchar](50) NULL,
  [accountNo] [nvarchar](50) NULL,
  [deliveryVIA] [nvarchar](50) NULL,
  [contact] [nvarchar](50) NULL,
  [delivery] [nvarchar](50) NULL,
  [freight] [smallmoney] NULL,
  [deleted] [bit] NULL CONSTRAINT [DF_ord_tblOrdersAudit_deleted_1] DEFAULT (0),
  [enteredBy] [nvarchar](50) NULL CONSTRAINT [DF_ord_tblOrdersAudit_enteredBy_1] DEFAULT (suser_sname()),
  [updatedBy] [nvarchar](50) NULL CONSTRAINT [DF_ord_tblOrdersAudit_updatedBy_1] DEFAULT (suser_sname()),
  [updateDate] [smalldatetime] NULL CONSTRAINT [DF_ord_tblOrdersAudit_updateDate_1] DEFAULT (getdate()),
  [createDate] [smalldatetime] NULL CONSTRAINT [DF_ord_tblOrdersAudit_createDate_1] DEFAULT (getdate()),
  [stockLocation] [int] NULL,
  [hidePrices] [bit] NULL CONSTRAINT [DF_ord_tblOrdersAudit_hidePrices_1] DEFAULT (0),
  [SupplierEmail] [nvarchar](100) NULL,
  [ordered] [bit] NULL CONSTRAINT [DF_ord_tblOrdersAudit_ordered_1] DEFAULT (0),
  [deliveryNote] [varchar](1000) NULL,
  [ynEdited] [bit] NULL CONSTRAINT [DF_ord_tblOrdersAudit_ynEdited_1] DEFAULT (0),
  [dtEDITimeStamp] [smalldatetime] NULL,
  [OLDsupplier] [nvarchar](50) NULL,
  [OLDsupplierFax] [varchar](15) NULL,
  [OLDsupplierPhone] [varchar](15) NULL,
  [OLDsupplierContact] [varchar](50) NULL,
  [OLDorderNote] [varchar](1000) NULL,
  [OLDorderDate] [smalldatetime] NULL,
  [OLDdespatchDateReq] [smalldatetime] NULL,
  [OLDservice] [nvarchar](50) NULL,
  [OLDaccountNo] [nvarchar](50) NULL,
  [OLDdeliveryVIA] [nvarchar](50) NULL,
  [OLDcontact] [nvarchar](50) NULL,
  [OLDdelivery] [nvarchar](50) NULL,
  [OLDfreight] [smallmoney] NULL,
  [OLDdeleted] [bit] NULL CONSTRAINT [DF_ord_tblOrdersAudit_OLDdeleted] DEFAULT (0),
  [OLDenteredBy] [nvarchar](50) NULL CONSTRAINT [DF_ord_tblOrdersAudit_OLDenteredBy] DEFAULT (suser_sname()),
  [OLDupdatedBy] [nvarchar](50) NULL CONSTRAINT [DF_ord_tblOrdersAudit_OLDupdatedBy] DEFAULT (suser_sname()),
  [OLDupdateDate] [smalldatetime] NULL CONSTRAINT [DF_ord_tblOrdersAudit_OLDupdateDate] DEFAULT (getdate()),
  [OLDcreateDate] [smalldatetime] NULL CONSTRAINT [DF_ord_tblOrdersAudit_OLDcreateDate] DEFAULT (getdate()),
  [OLDstockLocation] [int] NULL,
  [OLDhidePrices] [bit] NULL CONSTRAINT [DF_ord_tblOrdersAudit_OLDhidePrices] DEFAULT (0),
  [OLDSupplierEmail] [nvarchar](100) NULL,
  [OLDordered] [bit] NULL CONSTRAINT [DF_ord_tblOrdersAudit_OLDordered] DEFAULT (0),
  [OLDdeliveryNote] [varchar](1000) NULL,
  [OLDynEdited] [bit] NULL CONSTRAINT [DF_ord_tblOrdersAudit_OLDynEdited] DEFAULT (0),
  [OLDdtEDITimeStamp] [smalldatetime] NULL,
  CONSTRAINT [PK_ord_tblOrdersAudit] PRIMARY KEY CLUSTERED ([auditID])
)
ON [PRIMARY]
GO