CREATE TABLE [dbo].[jcm_JobVariations] (
  [Job ID] [int] NOT NULL,
  [Var No] [int] NOT NULL CONSTRAINT [DF_jcm_JobVariations_Var No] DEFAULT (0),
  [Var Date] [smalldatetime] NULL,
  [Var Description] [nvarchar](255) NULL,
  [Var Comment] [nvarchar](1000) NULL,
  [est A] [real] NULL,
  [est B] [real] NULL,
  [est D] [real] NULL,
  [est E] [real] NULL,
  [est L] [real] NULL,
  [est P] [real] NULL,
  [est S] [real] NULL,
  [est T] [real] NULL,
  [est W] [real] NULL,
  [est Prog] [real] NULL,
  [est Doc] [real] NULL,
  [est Warr] [real] NULL,
  [est Design] [real] NULL,
  [est Sup] [real] NULL,
  [est Quoted$] [money] NULL,
  [est Materials$] [money] NULL,
  [est Labour$] [money] NULL,
  [est Sundry$] [money] NULL,
  [est Labels$] [money] NULL,
  [est Freight$] [money] NULL,
  [est Contractor$] [money] NULL,
  [Quote No] [nvarchar](40) NULL,
  [Customer] [nvarchar](50) NULL,
  [Customer ABN] [nvarchar](25) NULL,
  [Order No] [nvarchar](20) NULL,
  [DrawingsReq] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_DrawingsReq] DEFAULT (0),
  [Drawings By] [smalldatetime] NULL,
  [Deliver By] [smalldatetime] NULL,
  [DeliverToSiteBy] [nvarchar](50) NULL,
  [LastModified] [smalldatetime] NULL CONSTRAINT [DF_jcm_JobVariations_LastModified] DEFAULT (getdate()),
  [OrderAckLetter] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_OrderAckLetter] DEFAULT (0),
  [FileTypeReq] [nvarchar](50) NULL,
  [IOMReq] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_IOMReq] DEFAULT (0),
  [EstablishedAcct] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_EstablishedAcct] DEFAULT (0),
  [CreditChecked] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_CreditChecked] DEFAULT (0),
  [CreditAppReq] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_CreditAppReq] DEFAULT (0),
  [SpecialInsDelv] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_SpecialInsDelv] DEFAULT (0),
  [ProfIndemnityHrs] [int] NULL,
  [ProfIndemnityRate] [money] NULL,
  [ProfIndemnityMaterial] [money] NULL,
  [SiteWorksHrs] [int] NULL,
  [SiteWorksRate] [money] NULL,
  [SiteWorksMaterial] [money] NULL,
  [MANSalesNo] [nvarchar](10) NULL,
  [MANAssbHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANAssbHrs] DEFAULT (0),
  [MANAssbRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANAssbRate] DEFAULT (0),
  [MANBusbarHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANBusbarHrs] DEFAULT (0),
  [MANBusbarRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANBusbarRate] DEFAULT (0),
  [MANLayoutHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANLayoutHrs] DEFAULT (0),
  [MANLayoutRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANLayoutRate] DEFAULT (0),
  [MANEscutHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANEscutHrs] DEFAULT (0),
  [MANEscutRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANEscutRate] DEFAULT (0),
  [MANPrepHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANPrepHrs] DEFAULT (0),
  [MANPrepRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANPrepRate] DEFAULT (0),
  [MANWiringHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANWiringHrs] DEFAULT (0),
  [MANWiringRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANWiringRate] DEFAULT (0),
  [MANSiteWorkHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANSiteWorkHrs] DEFAULT (0),
  [MANSiteWorkRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANSiteWorkRate] DEFAULT (0),
  [MANInstallationHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANInstallationHrs] DEFAULT (0),
  [MANInstallationRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANInstallationRate] DEFAULT (0),
  [MANTestingHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANTestingHrs] DEFAULT (0),
  [MANTestingRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANTestingRate] DEFAULT (0),
  [MANCommissioningHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANCommissioningHrs] DEFAULT (0),
  [MANCommissioningRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANCommissioningRate] DEFAULT (0),
  [MANProgrammingHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANProgrammingHrs] DEFAULT (0),
  [MANProgrammingRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANProgrammingRate] DEFAULT (0),
  [MANWarrantyHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANWarrantyHrs] DEFAULT (0),
  [MANWarrantyRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANWarrantyRate] DEFAULT (0),
  [MANDraftingHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANDraftingHrs] DEFAULT (0),
  [MANDraftingRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANDraftingRate] DEFAULT (0),
  [MANDesignHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANDesignHrs] DEFAULT (0),
  [MANDesignRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANDesignRate] DEFAULT (0),
  [MANSupervisionHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANSupervisionHrs] DEFAULT (0),
  [MANSupervisionRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANSupervisionRate] DEFAULT (0),
  [MANDocumentationHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_MANDocumentationHrs] DEFAULT (0),
  [MANDocumentationRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_MANDocumentationRate] DEFAULT (0),
  [ENGSalesNo] [nvarchar](10) NULL,
  [ENGAssbHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGAssbHrs] DEFAULT (0),
  [ENGAssbRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGAssbRate] DEFAULT (0),
  [ENGBusbarHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGBusbarHrs] DEFAULT (0),
  [ENGBusbarRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGBusbarRate] DEFAULT (0),
  [ENGLayoutHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGLayoutHrs] DEFAULT (0),
  [ENGLayoutRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGLayoutRate] DEFAULT (0),
  [ENGEscutHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGEscutHrs] DEFAULT (0),
  [ENGEscutRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGEscutRate] DEFAULT (0),
  [ENGPrepHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGPrepHrs] DEFAULT (0),
  [ENGPrepRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGPrepRate] DEFAULT (0),
  [ENGWiringHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGWiringHrs] DEFAULT (0),
  [ENGWiringRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGWiringRate] DEFAULT (0),
  [ENGSiteWorkHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGSiteWorkHrs] DEFAULT (0),
  [ENGSiteWorkRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGSiteWorkRate] DEFAULT (0),
  [ENGInstallationHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGInstallationHrs] DEFAULT (0),
  [ENGInstallationRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGInstallationRate] DEFAULT (0),
  [ENGTestingHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGTestingHrs] DEFAULT (0),
  [ENGTestingRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGTestingRate] DEFAULT (0),
  [ENGCommissioningHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGCommissioningHrs] DEFAULT (0),
  [ENGCommissioningRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGCommissioningRate] DEFAULT (0),
  [ENGProgrammingHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGProgrammingHrs] DEFAULT (0),
  [ENGProgrammingRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGProgrammingRate] DEFAULT (0),
  [ENGWarrantyHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGWarrantyHrs] DEFAULT (0),
  [ENGWarrantyRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGWarrantyRate] DEFAULT (0),
  [ENGDraftingHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGDraftingHrs] DEFAULT (0),
  [ENGDraftingRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGDraftingRate] DEFAULT (0),
  [ENGDesignHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGDesignHrs] DEFAULT (0),
  [ENGDesignRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGDesignRate] DEFAULT (0),
  [ENGSupervisionHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGSupervisionHrs] DEFAULT (0),
  [ENGSupervisionRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGSupervisionRate] DEFAULT (0),
  [ENGDocumentationHrs] [real] NULL CONSTRAINT [DF_jcm_JobVariations_ENGDocumentationHrs] DEFAULT (0),
  [ENGDocumentationRate] [money] NULL CONSTRAINT [DF_jcm_JobVariations_ENGDocumentationRate] DEFAULT (0),
  [incomplete] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_incomplete] DEFAULT (0),
  [commContact] [nvarchar](50) NULL,
  [techContact] [nvarchar](50) NULL,
  [phoneNo] [nvarchar](50) NULL,
  [faxNo] [nvarchar](50) NULL,
  [mobileNo] [nvarchar](50) NULL,
  [QSLevel] [nvarchar](1) NULL,
  [projectDividers] [nvarchar](50) NULL,
  [suppliersList] [nvarchar](50) NULL,
  [acctsAuthorised] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_authorised] DEFAULT (0),
  [acctsAuthDate] [datetime] NULL,
  [tonyAuthorised] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_tonyAuthorised] DEFAULT (0),
  [tonyAuthDate] [datetime] NULL,
  [jobAuthorised] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_tonyAuthorised1] DEFAULT (0),
  [jobAuthDate] [datetime] NULL,
  [MANTotalExcGST] [money] NULL,
  [MANCogsMat] [money] NULL,
  [MANSundry] [money] NULL,
  [MANLabels] [money] NULL,
  [MANFreight] [money] NULL,
  [MANSubCon] [money] NULL,
  [ENGTotalExcGST] [money] NULL,
  [ENGCogsMat] [money] NULL,
  [ENGSundry] [money] NULL,
  [ENGLabels] [money] NULL,
  [ENGFreight] [money] NULL,
  [ENGSubCon] [money] NULL,
  [AuditCreatedBy] [nvarchar](50) NULL CONSTRAINT [DF_jcm_JobVariations_AuditCreatedBy] DEFAULT (suser_sname()),
  [AuditCreated] [datetime] NULL CONSTRAINT [DF_jcm_JobVariations_AuditCreated] DEFAULT (getdate()),
  [AuditUpdatedBy] [nvarchar](50) NULL CONSTRAINT [DF_jcm_JobVariations_AuditUpdatedBy] DEFAULT (suser_sname()),
  [AuditUpdated] [datetime] NULL CONSTRAINT [DF_jcm_JobVariations_AuditUpdated] DEFAULT (getdate()),
  [originator] [nvarchar](50) NULL CONSTRAINT [DF_jcm_JobVariations_Originator] DEFAULT (suser_sname()),
  [entered by] [nvarchar](50) NULL,
  [startupSheet] [bit] NOT NULL CONSTRAINT [DF_jcm_JobVariations_startupSheet] DEFAULT (0),
  [AssignedTo] [nvarchar](50) NULL,
  [SUBCONTRACTORUSED] [bit] NOT NULL DEFAULT (0),
  CONSTRAINT [PK_jcm_JobVariations] PRIMARY KEY CLUSTERED ([Job ID], [Var No])
)
ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [trgDELETEJobVar] ON [dbo].[jcm_JobVariations] 
FOR DELETE
AS
INSERT INTO jcm_tblJobVariationsAudit
                      (AuditUser, AuditDate, AuditOperation, [Job ID], [OLDVar No], [OLDVar Date], [OLDVar Description], [OLDVar Comment], [OLDest A], [OLDest B], 
                      [OLDest D], [OLDest E], [OLDest L], [OLDest P], [OLDest S], [OLDest T], [OLDest W], [OLDest Prog], [OLDest Doc], [OLDest Warr], [OLDest Design], 
                      [OLDest Sup], [OLDest Quoted$], [OLDest Materials$], [OLDest Labour$], [OLDest Sundry$], [OLDest Labels$], [OLDest Freight$], [OLDest Contractor$], 
                     [OLDentered by], [OLDQuote No], OLDCustomer, [OLDCustomer ABN], [OLDOrderNo], OLDDrawingsReq, [OLDDrawings By], [OLDDeliver By], OLDDeliverToSiteBy, 
                      OLDLastModified, OLDOrderAckLetter, OLDFileTypeReq, OLDIOMReq, OLDEstablishedAcct, OLDCreditAppReq, OLDCreditChecked, OLDSpecialInsDelv, 
                      OLDProfIndemnityHrs, OLDProfIndemnityRate, OLDProfIndemnityMaterial, OLDSiteWorksHrs, OLDSiteWorksRate, OLDSiteWorksMaterial, 
                      OLDMANSalesNo, OLDMANAssbHrs, OLDMANAssbRate, OLDMANBusbarHrs, OLDMANBusbarRate, OLDMANLayoutHrs, OLDMANLayoutRate, 
                      OLDMANEscutHrs, OLDMANEscutRate, OLDMANPrepHrs, OLDMANPrepRate, OLDMANWiringHrs, OLDMANWiringRate, OLDMANSiteWorkHrs, 
                      OLDMANSiteWorkRate, OLDMANInstallationHrs, OLDMANInstallationRate, OLDMANTestingHrs, OLDMANTestingRate, OLDMANCommissioningHrs, 
                      OLDMANCommissioningRate, OLDMANProgrammingHrs, OLDMANProgrammingRate, OLDMANWarrantyHrs, OLDMANWarrantyRate, 
                      OLDMANDraftingHrs, OLDMANDraftingRate, OLDMANDesignHrs, OLDMANDesignRate, OLDMANSupervisionHrs, OLDMANSupervisionRate, 
                      OLDMANDocumentationHrs, OLDMANDocumentationRate, OLDENGSalesNo, OLDENGAssbHrs, OLDENGAssbRate, OLDENGBusbarHrs, 
                      OLDENGBusbarRate, OLDENGLayoutHrs, OLDENGLayoutRate, OLDENGEscutHrs, OLDENGEscutRate, OLDENGPrepHrs, OLDENGPrepRate, 
                      OLDENGWiringHrs, OLDENGWiringRate, OLDENGSiteWorkHrs, OLDENGSiteWorkRate, OLDENGInstallationHrs, OLDENGInstallationRate, 
                      OLDENGTestingHrs, OLDENGCommissioningHrs, OLDENGTestingRate, OLDENGCommissioningRate, OLDENGProgrammingHrs, 
                      OLDENGProgrammingRate, OLDENGWarrantyHrs, OLDENGWarrantyRate, OLDENGDraftingHrs, OLDENGDraftingRate, OLDENGDesignHrs, 
                      OLDENGDesignRate, OLDENGSupervisionHrs, OLDENGSupervisionRate, OLDENGDocumentationHrs, OLDENGDocumentationRate, OLDincomplete, 
                      OLDcommContact, OLDtechContact, OLDphoneNo, OLDfaxNo, OLDmobileNo, OLDQSLevel, OLDprojectDividers, OLDsuppliersList, 
                      OLDacctsAuthorised, OLDacctsAuthDate, OLDtonyAuthorised, OLDtonyAuthDate, OLDjobAuthorised, OLDjobAuthDate, OLDMANTotalExcGST, 
                      OLDMANCogsMat, OLDMANSundry, OLDMANLabels, OLDMANFreight, OLDMANSubCon, OLDENGTotalExcGST, OLDENGCogsMat, OLDENGSundry, 
                      OLDENGLabels, OLDENGFreight, OLDENGSubCon, OLDoriginator)
SELECT     SYSTEM_USER AS Expr1, GETDATE() AS Expr2, 'DELETE' AS Expr3, [Job ID], [Var No], [Var Date], [Var Description], [Var Comment], [est A], [est B], 
                      [est D], [est E], [est L], [est P], [est S], [est T], [est W], [est Prog], [est Doc], [est Warr], [est Design], [est Sup], [est Quoted$], [est Materials$], 
                      [est Labour$], [est Sundry$], [est Labels$], [est Freight$], [est Contractor$],[entered by], [Quote No], Customer, [Customer ABN], [Order No], DrawingsReq, 
                      [Drawings By], [Deliver By], DeliverToSiteBy, LastModified, OrderAckLetter, FileTypeReq, IOMReq, EstablishedAcct, CreditAppReq, CreditChecked, 
                      SpecialInsDelv, ProfIndemnityHrs, ProfIndemnityRate, ProfIndemnityMaterial, SiteWorksHrs, SiteWorksRate, SiteWorksMaterial, MANSalesNo, 
                      MANAssbHrs, MANAssbRate, MANBusbarHrs, MANBusbarRate, MANLayoutHrs, MANLayoutRate, MANEscutHrs, MANEscutRate, MANPrepHrs, 
                      MANPrepRate, MANWiringHrs, MANWiringRate, MANSiteWorkHrs, MANSiteWorkRate, MANInstallationHrs, MANInstallationRate, MANTestingHrs, 
                      MANTestingRate, MANCommissioningHrs, MANCommissioningRate, MANProgrammingHrs, MANProgrammingRate, MANWarrantyHrs, 
                      MANWarrantyRate, MANDraftingHrs, MANDraftingRate, MANDesignHrs, MANDesignRate, MANSupervisionHrs, MANSupervisionRate, 
                      MANDocumentationHrs, MANDocumentationRate, ENGSalesNo, ENGAssbHrs, ENGAssbRate, ENGBusbarHrs, ENGBusbarRate, ENGLayoutHrs, 
                      ENGLayoutRate, ENGEscutHrs, ENGEscutRate, ENGPrepHrs, ENGPrepRate, ENGWiringHrs, ENGWiringRate, ENGSiteWorkHrs, ENGSiteWorkRate, 
                      ENGInstallationHrs, ENGInstallationRate, ENGTestingHrs, ENGCommissioningHrs, ENGTestingRate, ENGCommissioningRate, ENGProgrammingHrs, 
                      ENGProgrammingRate, ENGWarrantyHrs, ENGWarrantyRate, ENGDraftingHrs, ENGDraftingRate, ENGDesignHrs, ENGDesignRate, 
                      ENGSupervisionHrs, ENGSupervisionRate, ENGDocumentationHrs, ENGDocumentationRate, incomplete, commContact, techContact, phoneNo, faxNo, 
                      mobileNo, QSLevel, projectDividers, suppliersList, acctsAuthorised, acctsAuthDate, tonyAuthorised, tonyAuthDate, jobAuthorised, jobAuthDate, 
                      MANTotalExcGST, MANCogsMat, MANSundry, MANLabels, MANFreight, MANSubCon, ENGTotalExcGST, ENGCogsMat, ENGSundry, ENGLabels, 
                      ENGFreight, ENGSubCon, originator
FROM         deleted
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [trgINSERTJobVar] ON [dbo].[jcm_JobVariations] 
FOR INSERT
AS
INSERT INTO jcm_tblJobVariationsAudit
                      (AuditUser, AuditDate, AuditOperation, [Job ID], [Var No], [Var Date], [Var Description], [Var Comment], [est A], [est B], [est D], [est E], [est L], [est P], 
                      [est S], [est T], [est W], [est Prog], [est Doc], [est Warr], [est Design], [est Sup], [est Quoted$], [est Materials$], [est Labour$], [est Sundry$], 
                      [est Labels$], [est Freight$], [est Contractor$], [entered by], [Quote No], Customer, [Customer ABN], [Order No], DrawingsReq, [Drawings By], 
                      [Deliver By], DeliverToSiteBy, LastModified, OrderAckLetter, FileTypeReq, IOMReq, EstablishedAcct, CreditAppReq, CreditChecked, SpecialInsDelv, 
                      ProfIndemnityHrs, ProfIndemnityRate, ProfIndemnityMaterial, SiteWorksHrs, SiteWorksRate, SiteWorksMaterial, MANSalesNo, MANAssbHrs, 
                      MANAssbRate, MANBusbarHrs, MANBusbarRate, MANLayoutHrs, MANLayoutRate, MANEscutHrs, MANEscutRate, MANPrepHrs, MANPrepRate, 
                      MANWiringHrs, MANWiringRate, MANSiteWorkHrs, MANSiteWorkRate, MANInstallationHrs, MANInstallationRate, MANTestingHrs, MANTestingRate, 
                      MANCommissioningHrs, MANCommissioningRate, MANProgrammingHrs, MANProgrammingRate, MANWarrantyHrs, MANWarrantyRate, 
                      MANDraftingHrs, MANDraftingRate, MANDesignHrs, MANDesignRate, MANSupervisionHrs, MANSupervisionRate, MANDocumentationHrs, 
                      MANDocumentationRate, ENGSalesNo, ENGAssbHrs, ENGAssbRate, ENGBusbarHrs, ENGBusbarRate, ENGLayoutHrs, ENGLayoutRate, ENGEscutHrs, 
                      ENGEscutRate, ENGPrepHrs, ENGPrepRate, ENGWiringHrs, ENGWiringRate, ENGSiteWorkHrs, ENGSiteWorkRate, ENGInstallationHrs, 
                      ENGInstallationRate, ENGTestingHrs, ENGCommissioningHrs, ENGTestingRate, ENGCommissioningRate, ENGProgrammingHrs, 
                      ENGProgrammingRate, ENGWarrantyHrs, ENGWarrantyRate, ENGDraftingHrs, ENGDraftingRate, ENGDesignHrs, ENGDesignRate, 
                      ENGSupervisionHrs, ENGSupervisionRate, ENGDocumentationHrs, ENGDocumentationRate, incomplete, commContact, techContact, phoneNo, faxNo, 
                      mobileNo, QSLevel, projectDividers, suppliersList, acctsAuthorised, acctsAuthDate, tonyAuthorised, tonyAuthDate, jobAuthorised, jobAuthDate, 
                      MANTotalExcGST, MANCogsMat, MANSundry, MANLabels, MANFreight, MANSubCon, ENGTotalExcGST, ENGCogsMat, ENGSundry, ENGLabels, 
                      ENGFreight, ENGSubCon, originator)
SELECT     SYSTEM_USER AS Expr1, GETDATE() AS Expr2, 'INSERT' AS Expr3, [Job ID], [Var No], [Var Date], [Var Description], [Var Comment], [est A], [est B], 
                      [est D], [est E], [est L], [est P], [est S], [est T], [est W], [est Prog], [est Doc], [est Warr], [est Design], [est Sup], [est Quoted$], [est Materials$], 
                      [est Labour$], [est Sundry$], [est Labels$], [est Freight$], [est Contractor$], [entered by], [Quote No], Customer, [Customer ABN], [Order No], 
                      DrawingsReq, [Drawings By], [Deliver By], DeliverToSiteBy, LastModified, OrderAckLetter, FileTypeReq, IOMReq, EstablishedAcct, CreditAppReq, 
                      CreditChecked, SpecialInsDelv, ProfIndemnityHrs, ProfIndemnityRate, ProfIndemnityMaterial, SiteWorksHrs, SiteWorksRate, SiteWorksMaterial, 
                      MANSalesNo, MANAssbHrs, MANAssbRate, MANBusbarHrs, MANBusbarRate, MANLayoutHrs, MANLayoutRate, MANEscutHrs, MANEscutRate, 
                      MANPrepHrs, MANPrepRate, MANWiringHrs, MANWiringRate, MANSiteWorkHrs, MANSiteWorkRate, MANInstallationHrs, MANInstallationRate, 
                      MANTestingHrs, MANTestingRate, MANCommissioningHrs, MANCommissioningRate, MANProgrammingHrs, MANProgrammingRate, MANWarrantyHrs, 
                      MANWarrantyRate, MANDraftingHrs, MANDraftingRate, MANDesignHrs, MANDesignRate, MANSupervisionHrs, MANSupervisionRate, 
                      MANDocumentationHrs, MANDocumentationRate, ENGSalesNo, ENGAssbHrs, ENGAssbRate, ENGBusbarHrs, ENGBusbarRate, ENGLayoutHrs, 
                      ENGLayoutRate, ENGEscutHrs, ENGEscutRate, ENGPrepHrs, ENGPrepRate, ENGWiringHrs, ENGWiringRate, ENGSiteWorkHrs, ENGSiteWorkRate, 
                      ENGInstallationHrs, ENGInstallationRate, ENGTestingHrs, ENGCommissioningHrs, ENGTestingRate, ENGCommissioningRate, ENGProgrammingHrs, 
                      ENGProgrammingRate, ENGWarrantyHrs, ENGWarrantyRate, ENGDraftingHrs, ENGDraftingRate, ENGDesignHrs, ENGDesignRate, 
                      ENGSupervisionHrs, ENGSupervisionRate, ENGDocumentationHrs, ENGDocumentationRate, incomplete, commContact, techContact, phoneNo, faxNo, 
                      mobileNo, QSLevel, projectDividers, suppliersList, acctsAuthorised, acctsAuthDate, tonyAuthorised, tonyAuthDate, jobAuthorised, jobAuthDate, 
                      MANTotalExcGST, MANCogsMat, MANSundry, MANLabels, MANFreight, MANSubCon, ENGTotalExcGST, ENGCogsMat, ENGSundry, ENGLabels, 
                      ENGFreight, ENGSubCon, originator
FROM         inserted
GO

SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE TRIGGER [trgUPDATEJobVar] ON [dbo].[jcm_JobVariations] 
FOR UPDATE
AS
Update  [dbo].[jcm_JobVariations] set [auditupdated] = getdate(), [auditupdatedby] = system_user
from [dbo].[jcm_JobVariations], inserted
where  [dbo].[jcm_JobVariations].[job id] = inserted.[job id] and  [dbo].[jcm_JobVariations].[var no] = inserted.[var no]
INSERT into jcm_tblJobVariationsAudit (AuditUser, AuditDate, AuditOperation, [Job ID], [Var No], [Var Date], [Var Description], [Var Comment], [est A], [est B], [est D], [est E], [est L], [est P], 
                      [est S], [est T], [est W], [est Prog], [est Doc], [est Warr], [est Design], [est Sup], [est Quoted$], [est Materials$], [est Labour$], [est Sundry$], 
                      [est Labels$], [est Freight$], [est Contractor$],[entered by], [Quote No], Customer, [Customer ABN], [Order No], DrawingsReq, [Drawings By], [Deliver By], 
                      DeliverToSiteBy, LastModified, OrderAckLetter, FileTypeReq, IOMReq, EstablishedAcct, CreditAppReq, CreditChecked, SpecialInsDelv, 
                      ProfIndemnityHrs, ProfIndemnityRate, ProfIndemnityMaterial, SiteWorksHrs, SiteWorksRate, SiteWorksMaterial, MANSalesNo, MANAssbHrs, 
                      MANAssbRate, MANBusbarHrs, MANBusbarRate, MANLayoutHrs, MANLayoutRate, MANEscutHrs, MANEscutRate, MANPrepHrs, MANPrepRate, 
                      MANWiringHrs, MANWiringRate, MANSiteWorkHrs, MANSiteWorkRate, MANInstallationHrs, MANInstallationRate, MANTestingHrs, MANTestingRate, 
                      MANCommissioningHrs, MANCommissioningRate, MANProgrammingHrs, MANProgrammingRate, MANWarrantyHrs, MANWarrantyRate, 
                      MANDraftingHrs, MANDraftingRate, MANDesignHrs, MANDesignRate, MANSupervisionHrs, MANSupervisionRate, MANDocumentationHrs, 
                      MANDocumentationRate, ENGSalesNo, ENGAssbHrs, ENGAssbRate, ENGBusbarHrs, ENGBusbarRate, ENGLayoutHrs, ENGLayoutRate, ENGEscutHrs, 
                      ENGEscutRate, ENGPrepHrs, ENGPrepRate, ENGWiringHrs, ENGWiringRate, ENGSiteWorkHrs, ENGSiteWorkRate, ENGInstallationHrs, 
                      ENGInstallationRate, ENGTestingHrs, ENGCommissioningHrs, ENGTestingRate, ENGCommissioningRate, ENGProgrammingHrs, 
                      ENGProgrammingRate, ENGWarrantyHrs, ENGWarrantyRate, ENGDraftingHrs, ENGDraftingRate, ENGDesignHrs, ENGDesignRate, 
                      ENGSupervisionHrs, ENGSupervisionRate, ENGDocumentationHrs, ENGDocumentationRate, incomplete, commContact, techContact, phoneNo, faxNo, 
                      mobileNo, QSLevel, projectDividers, suppliersList, acctsAuthorised, acctsAuthDate, tonyAuthorised, tonyAuthDate, jobAuthorised, jobAuthDate, 
                      MANTotalExcGST, MANCogsMat, MANSundry, MANLabels, MANFreight, MANSubCon, ENGTotalExcGST, ENGCogsMat, ENGSundry, ENGLabels, 
                      ENGFreight, ENGSubCon, originator, [OLDVar No], [OLDVar Date], [OLDVar Description], [OLDVar Comment], [OLDest A], [OLDest B], [OLDest D], [OLDest E], [OLDest L], [OLDest P], [OLDest S], [OLDest T], [OLDest W], [OLDest Prog], [OLDest Doc], [OLDest Warr], [OLDest Design], [OLDest Sup], [OLDest Quoted$], [OLDest Materials$], [OLDest Labour$], [OLDest Sundry$], 
                      [OLDest Labels$], [OLDest Freight$], [OLDest Contractor$],[oldentered by], [OLDQuote No], OLDCustomer, [OLDCustomer ABN], [OLDOrder No], OLDDrawingsReq, [OLDDrawings By], [OLDDeliver By], 
OLDDeliverToSiteBy, OLDLastModified, OLDOrderAckLetter, OLDFileTypeReq, OLDIOMReq, OLDEstablishedAcct, OLDCreditAppReq, OLDCreditChecked, OLDSpecialInsDelv, OLDProfIndemnityHrs, OLDProfIndemnityRate, OLDProfIndemnityMaterial, OLDSiteWorksHrs, OLDSiteWorksRate, OLDSiteWorksMaterial, OLDMANSalesNo, OLDMANAssbHrs, OLDMANAssbRate, OLDMANBusbarHrs, OLDMANBusbarRate, OLDMANLayoutHrs, OLDMANLayoutRate, OLDMANEscutHrs, OLDMANEscutRate, OLDMANPrepHrs, OLDMANPrepRate, OLDMANWiringHrs, OLDMANWiringRate, OLDMANSiteWorkHrs, OLDMANSiteWorkRate, OLDMANInstallationHrs, OLDMANInstallationRate, OLDMANTestingHrs, OLDMANTestingRate, OLDMANCommissioningHrs, OLDMANCommissioningRate, OLDMANProgrammingHrs, OLDMANProgrammingRate, OLDMANWarrantyHrs, OLDMANWarrantyRate, OLDMANDraftingHrs, OLDMANDraftingRate, OLDMANDesignHrs, OLDMANDesignRate, OLDMANSupervisionHrs, OLDMANSupervisionRate, OLDMANDocumentationHrs, OLDMANDocumentationRate, OLDENGSalesNo, OLDENGAssbHrs, OLDENGAssbRate, OLDENGBusbarHrs, OLDENGBusbarRate, OLDENGLayoutHrs, OLDENGLayoutRate, OLDENGEscutHrs, OLDENGEscutRate, OLDENGPrepHrs, OLDENGPrepRate, OLDENGWiringHrs, OLDENGWiringRate, OLDENGSiteWorkHrs, OLDENGSiteWorkRate, OLDENGInstallationHrs, OLDENGInstallationRate, OLDENGTestingHrs, OLDENGCommissioningHrs, OLDENGTestingRate, OLDENGCommissioningRate, OLDENGProgrammingHrs, OLDENGProgrammingRate, OLDENGWarrantyHrs, OLDENGWarrantyRate, OLDENGDraftingHrs, OLDENGDraftingRate, OLDENGDesignHrs, OLDENGDesignRate, OLDENGSupervisionHrs, OLDENGSupervisionRate, OLDENGDocumentationHrs, OLDENGDocumentationRate, OLDincomplete, OLDcommContact, OLDtechContact, OLDphoneNo, OLDfaxNo, OLDmobileNo, OLDQSLevel, OLDprojectDividers, OLDsuppliersList, OLDacctsAuthorised, OLDacctsAuthDate, OLDtonyAuthorised, OLDtonyAuthDate, OLDjobAuthorised, OLDjobAuthDate, OLDMANTotalExcGST, OLDMANCogsMat, OLDMANSundry, OLDMANLabels, OLDMANFreight, OLDMANSubCon, OLDENGTotalExcGST, OLDENGCogsMat, OLDENGSundry, OLDENGLabels, OLDENGFreight, OLDENGSubCon, OLDoriginator)
SELECT     system_user, getdate(), 'UPDATE', ins.[Job ID], ins.[Var No], ins.[Var Date], ins.[Var Description], ins.[Var Comment], ins.[est A], ins.[est B], ins.[est D], ins.[est E], ins.[est L], ins.[est P], ins.[est S], ins.[est T], ins.[est W], ins.[est Prog], ins.[est Doc], ins.[est Warr], ins.[est Design], ins.[est Sup], ins.[est Quoted$], ins.[est Materials$], ins.[est Labour$], ins.[est Sundry$], ins.[est Labels$], ins.[est Freight$], ins.[est Contractor$],ins.[entered by], ins.[Quote No], ins.Customer, ins.[Customer ABN], ins.[Order No], ins.DrawingsReq, ins.[Drawings By], ins.[Deliver By], ins.DeliverToSiteBy, ins.LastModified, ins.OrderAckLetter, ins.FileTypeReq, ins.IOMReq, ins.EstablishedAcct, ins.CreditAppReq, ins.CreditChecked, ins.SpecialInsDelv, ins.ProfIndemnityHrs, ins.ProfIndemnityRate, ins.ProfIndemnityMaterial, ins.SiteWorksHrs, ins.SiteWorksRate, ins.SiteWorksMaterial, ins.MANSalesNo, ins.MANAssbHrs, ins.MANAssbRate, ins.MANBusbarHrs, ins.MANBusbarRate, ins.MANLayoutHrs, ins.MANLayoutRate, ins.MANEscutHrs, ins.MANEscutRate, ins.MANPrepHrs, ins.MANPrepRate, ins.MANWiringHrs, ins.MANWiringRate, ins.MANSiteWorkHrs, ins.MANSiteWorkRate, ins.MANInstallationHrs, ins.MANInstallationRate, ins.MANTestingHrs, ins.MANTestingRate, ins.MANCommissioningHrs, ins.MANCommissioningRate, ins.MANProgrammingHrs, ins.MANProgrammingRate, ins.MANWarrantyHrs, ins.MANWarrantyRate, ins.MANDraftingHrs, ins.MANDraftingRate, ins.MANDesignHrs, ins.MANDesignRate, ins.MANSupervisionHrs, ins.MANSupervisionRate, ins.MANDocumentationHrs, ins.MANDocumentationRate, ins.ENGSalesNo, ins.ENGAssbHrs, ins.ENGAssbRate, ins.ENGBusbarHrs, ins.ENGBusbarRate, ins.ENGLayoutHrs, ins.ENGLayoutRate, ins.ENGEscutHrs, ins.ENGEscutRate, ins.ENGPrepHrs, ins.ENGPrepRate, ins.ENGWiringHrs, ins.ENGWiringRate, ins.ENGSiteWorkHrs, ins.ENGSiteWorkRate, ins.ENGInstallationHrs, ins.ENGInstallationRate, ins.ENGTestingHrs, ins.ENGCommissioningHrs, ins.ENGTestingRate, ins.ENGCommissioningRate, ins.ENGProgrammingHrs, ins.ENGProgrammingRate, ins.ENGWarrantyHrs, ins.ENGWarrantyRate, ins.ENGDraftingHrs, ins.ENGDraftingRate, ins.ENGDesignHrs, ins.ENGDesignRate, ins.ENGSupervisionHrs, ins.ENGSupervisionRate, ins.ENGDocumentationHrs, ins.ENGDocumentationRate, ins.incomplete, ins.commContact, ins.techContact, ins.phoneNo, ins.faxNo, ins.mobileNo, ins.QSLevel, ins.projectDividers, ins.suppliersList, ins.acctsAuthorised, ins.acctsAuthDate, ins.tonyAuthorised, ins.tonyAuthDate, ins.jobAuthorised, ins.jobAuthDate, ins.MANTotalExcGST, ins.MANCogsMat, ins.MANSundry, ins.MANLabels, ins.MANFreight, ins.MANSubCon, ins.ENGTotalExcGST, ins.ENGCogsMat, ins.ENGSundry, ins.ENGLabels, ins.ENGFreight, ins.ENGSubCon, ins.originator,del.[Var No], del.[Var Date], del.[Var Description], del.[Var Comment], del.[est A], del.[est B], del.[est D], del.[est E], del.[est L], del.[est P], del.[est S], del.[est T], del.[est W], del.[est Prog], del.[est Doc], del.[est Warr], del.[est Design], del.[est Sup], del.[est Quoted$], del.[est Materials$], del.[est Labour$], del.[est Sundry$], del.[est Labels$], del.[est Freight$], del.[est Contractor$], del.[entered by], del.[Quote No], del.Customer, del.[Customer ABN], del.[Order No], del.DrawingsReq, del.[Drawings By], del.[Deliver By], del.DeliverToSiteBy, del.LastModified, del.OrderAckLetter, del.FileTypeReq, del.IOMReq, del.EstablishedAcct, del.CreditAppReq, del.CreditChecked, del.SpecialInsDelv, del.ProfIndemnityHrs, del.ProfIndemnityRate, del.ProfIndemnityMaterial, del.SiteWorksHrs, del.SiteWorksRate, del.SiteWorksMaterial, del.MANSalesNo, del.MANAssbHrs, del.MANAssbRate, del.MANBusbarHrs, del.MANBusbarRate, del.MANLayoutHrs, del.MANLayoutRate, del.MANEscutHrs, del.MANEscutRate, del.MANPrepHrs, del.MANPrepRate, del.MANWiringHrs, del.MANWiringRate, del.MANSiteWorkHrs, del.MANSiteWorkRate, del.MANInstallationHrs, del.MANInstallationRate, del.MANTestingHrs, del.MANTestingRate, del.MANCommissioningHrs, del.MANCommissioningRate, del.MANProgrammingHrs, del.MANProgrammingRate, del.MANWarrantyHrs, del.MANWarrantyRate, del.MANDraftingHrs, del.MANDraftingRate, del.MANDesignHrs, del.MANDesignRate, del.MANSupervisionHrs, del.MANSupervisionRate, del.MANDocumentationHrs, del. MANDocumentationRate, del.ENGSalesNo, del.ENGAssbHrs, del.ENGAssbRate, del.ENGBusbarHrs, del.ENGBusbarRate, del.ENGLayoutHrs, del.ENGLayoutRate, del.ENGEscutHrs, del. ENGEscutRate, del.ENGPrepHrs, del.ENGPrepRate, del.ENGWiringHrs, del.ENGWiringRate, del.ENGSiteWorkHrs, del.ENGSiteWorkRate, del.ENGInstallationHrs, del.ENGInstallationRate, del.ENGTestingHrs, del.ENGCommissioningHrs, del.ENGTestingRate, del.ENGCommissioningRate, del.ENGProgrammingHrs, del.ENGProgrammingRate, del.ENGWarrantyHrs, del.ENGWarrantyRate, del.ENGDraftingHrs, del.ENGDraftingRate, del.ENGDesignHrs, del.ENGDesignRate, del.ENGSupervisionHrs, del.ENGSupervisionRate, del.ENGDocumentationHrs, del.ENGDocumentationRate, del.incomplete, del.commContact, del.techContact, del.phoneNo, del.faxNo, del.mobileNo, del.QSLevel, del.projectDividers, del.suppliersList, del.acctsAuthorised, del.acctsAuthDate, del.tonyAuthorised, del.tonyAuthDate, del.jobAuthorised, del.jobAuthDate, del.MANTotalExcGST, del.MANCogsMat, del.MANSundry, del.MANLabels, del.MANFreight, del.MANSubCon, del.ENGTotalExcGST, del.ENGCogsMat, del.ENGSundry, del.ENGLabels, del. ENGFreight, del.ENGSubCon, del.originator
FROM         inserted ins, deleted del
GO