CREATE TABLE [dbo].[MODULE_SUMMARY_DEFAULT_W] (
  [freight] [money] NOT NULL CONSTRAINT [DF_MODULE_SUMMARY_DEFAULT_W_freight] DEFAULT (0),
  [sundry] [money] NOT NULL CONSTRAINT [DF_MODULE_SUMMARY_DEFAULT_W_sundry] DEFAULT (0),
  CONSTRAINT [PK_MODULE_SUMMARY_DEFAULT_W] PRIMARY KEY CLUSTERED ([freight], [sundry])
)
ON [PRIMARY]
GO