CREATE TABLE [fc].[tblInvoicePartsAudit] (
  [AuditID] [int] IDENTITY,
  [lngInvoiceID] [int] NOT NULL,
  [lngPartOrder] [int] NULL,
  [sngQty] [int] NULL,
  [strDescription] [nvarchar](255) NULL,
  [strStockCode] [nvarchar](50) NULL,
  [curSellPrice] [money] NULL,
  [sngDiscount] [real] NULL,
  [strBrand] [nvarchar](50) NULL,
  [strSupplierPartCode] [nvarchar](50) NULL,
  [lngUnitOfMeasure] [int] NULL,
  [curCostPriceLPP] [money] NULL,
  [strJobNo] [nvarchar](50) NULL,
  [curCreditOrigSell] [money] NULL,
  [ynInventoryItem] [bit] NOT NULL,
  [strGSTCat] [nvarchar](1) NULL,
  [sngGSTRate] [real] NULL,
  [lngPartGroupID] [int] NULL,
  [ynGroupDisc] [bit] NOT NULL,
  [ynClientDisc] [bit] NOT NULL,
  [ynNetPrice] [bit] NOT NULL,
  [curTotalPrice] [money] NULL,
  [lngPartNoteID] [int] NULL,
  [bytSheilaCodeType] [tinyint] NULL,
  [strISASOrderNo] [nvarchar](35) NULL,
  [invPartID] [int] NOT NULL,
  [CMItemID] [int] NULL,
  [oldlngPartOrder] [int] NULL,
  [oldsngQty] [int] NULL,
  [oldstrDescription] [nvarchar](255) NULL,
  [oldstrStockCode] [nvarchar](50) NULL,
  [oldcurSellPrice] [money] NULL,
  [oldsngDiscount] [real] NULL,
  [oldstrBrand] [nvarchar](50) NULL,
  [oldstrSupplierPartCode] [nvarchar](50) NULL,
  [oldlngUnitOfMeasure] [int] NULL,
  [oldcurCostPriceLPP] [money] NULL,
  [oldstrJobNo] [nvarchar](50) NULL,
  [oldcurCreditOrigSell] [money] NULL,
  [oldynInventoryItem] [bit] NOT NULL,
  [oldstrGSTCat] [nvarchar](1) NULL,
  [oldsngGSTRate] [real] NULL,
  [oldlngPartGroupID] [int] NULL,
  [oldynGroupDisc] [bit] NOT NULL,
  [oldynClientDisc] [bit] NOT NULL,
  [oldynNetPrice] [bit] NOT NULL,
  [oldcurTotalPrice] [money] NULL,
  [oldlngPartNoteID] [int] NULL,
  [oldbytSheilaCodeType] [tinyint] NULL,
  [oldstrISASOrderNo] [nvarchar](35) NULL,
  [oldCMItemID] [int] NULL,
  [Audit_User] [nvarchar](50) NOT NULL,
  [Audit_Date] [datetime] NOT NULL,
  [Audit_Operation] [nvarchar](10) NOT NULL,
  CONSTRAINT [PK_tblInvoicePartsAudit] PRIMARY KEY CLUSTERED ([AuditID])
)
ON [PRIMARY]
GO