CREATE TABLE [fc].[tblInvoiceDetails] (
  [lngInvoiceID] [int] IDENTITY,
  [lngCompanyID] [int] NOT NULL,
  [lngCustomerID] [int] NULL,
  [strInvoiceNo] [nvarchar](50) NOT NULL,
  [strOrderNo] [nvarchar](50) NULL,
  [strUserCode] [nvarchar](50) NULL,
  [ynQuote] [bit] NOT NULL CONSTRAINT [DF_tblInvoiceDetails_ynQuote] DEFAULT (0),
  [memDeliveryDetails] [varchar](400) NULL,
  [dtInvoiceDate] [smalldatetime] NULL CONSTRAINT [DF_tblInvoiceDetails_dtInvoiceDate] DEFAULT (getdate()),
  [strCustomerName] [nvarchar](50) NULL,
  [strElecTransNo] [nvarchar](50) NULL,
  [strConNoteNo] [nvarchar](25) NULL,
  [strCourierName] [nvarchar](50) NULL,
  [dtEDITimeStamp] [smalldatetime] NULL,
  [ynDeleted] [bit] NOT NULL CONSTRAINT [DF_tblInvoiceDetails_ynDeleted] DEFAULT (0),
  [dtDespatchDate] [smalldatetime] NULL,
  [dtOrderDate] [smalldatetime] NULL,
  [strSheilaTransType] [nvarchar](3) NULL,
  [lngCreditFromInvoiceID] [int] NULL,
  [ynEdited] [bit] NOT NULL CONSTRAINT [DF_tblInvoiceDetails_ynEdited] DEFAULT (0),
  [ynOnHold] [bit] NOT NULL CONSTRAINT [DF_tblInvoiceDetails_ynOnHold] DEFAULT (0),
  [dtQuoteValidUntil] [smalldatetime] NULL,
  [ynContract] [bit] NOT NULL CONSTRAINT [DF_tblInvoiceDetails_ynContract_1] DEFAULT (0),
  [requestedBy] [nvarchar](100) NULL,
  [ShipmentNo] [int] NULL,
  [strTechReportFile] [nvarchar](255) NULL,
  [strJSEAReportFile] [nvarchar](255) NULL,
  [strSuppDocReportFile] [nvarchar](255) NULL,
  [memCommentsIUO] [varchar](400) NULL,
  CONSTRAINT [PK_tblInvoiceDetails] PRIMARY KEY CLUSTERED ([lngInvoiceID]),
  CONSTRAINT [IX_tblInvoiceDetails] UNIQUE ([strInvoiceNo]),
  CONSTRAINT [IX_tblInvoiceDetails_1] UNIQUE ([strInvoiceNo])
)
ON [PRIMARY]
GO