CREATE TABLE [qm].[job_sheet_parts] (
  [jspartsid] [int] IDENTITY,
  [job_sheet_id] [int] NULL,
  [order_no] [nvarchar](30) NULL,
  [order?] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_order?] DEFAULT (0),
  [supplier] [nvarchar](50) NULL,
  [brand] [nvarchar](30) NULL,
  [cat_no] [nvarchar](50) NULL,
  [description] [nvarchar](300) NULL,
  [secondary_part_code] [nvarchar](25) NULL,
  [comment] [nvarchar](1000) NULL,
  [price] [money] NULL,
  [disc] [real] NULL,
  [qty] [real] NULL,
  [other_qty] [real] NULL,
  [ordered] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_ordered] DEFAULT (0),
  [proposed] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_proposed] DEFAULT (0),
  [order date] [smalldatetime] NULL,
  [UOM] [nvarchar](50) NULL,
  [date_due] [smalldatetime] NULL,
  [date_expected] [smalldatetime] NULL,
  [received] [bit] NOT NULL CONSTRAINT [DF_job_sheet_parts_received_1] DEFAULT (0),
  [supplier_cat_no] [nvarchar](50) NULL,
  [option] [nvarchar](50) NULL,
  [item_no] [int] NULL,
  [book_to] [nvarchar](50) NULL,
  [small_job_no] [nvarchar](50) NULL,
  [supplier_id] [int] NULL,
  [cost_price_lpp] [smallmoney] NULL,
  [line_type] [nvarchar](1) NULL,
  [gst_cat] [nvarchar](50) NULL,
  [conversion] [numeric] NULL CONSTRAINT [DF_job_sheet_parts_conversion_1] DEFAULT (1),
  [partid] [int] NULL,
  [qty_rec] [int] NULL,
  [qty_due] [int] NULL,
  [qty_inv] [int] NULL,
  [date_rec] [smalldatetime] NULL,
  [date_inv] [smalldatetime] NULL,
  [VisionRecordNo] [int] NULL,
  [DateUpdatedVision] [smalldatetime] NULL,
  [QuoteRef] [nvarchar](50) NULL,
  [CMPartID] [int] NULL,
  [qty_transit] [int] NULL,
  [UpdateDate] [datetime] NULL,
  [UpdateBy] [nvarchar](20) NULL,
  CONSTRAINT [PK_job_sheet_parts] PRIMARY KEY CLUSTERED ([jspartsid])
)
ON [PRIMARY]
GO