CREATE TABLE [qm].[module_summary] (
  [module_name] [nvarchar](195) NOT NULL,
  [date_last_modified] [smalldatetime] NULL,
  [last_mod_by_user] [nvarchar](30) NULL,
  [freight] [money] NULL CONSTRAINT [DF_module_summary_freight] DEFAULT (0),
  [sundry] [money] NULL CONSTRAINT [DF_module_summary_sundry] DEFAULT (0),
  [commissioning] [real] NULL CONSTRAINT [DF_module_summary_commissioning] DEFAULT (0),
  [documentation] [real] NULL CONSTRAINT [DF_module_summary_documentation] DEFAULT (0),
  [installation] [real] NULL CONSTRAINT [DF_module_summary_installation] DEFAULT (0),
  [programming] [real] NULL CONSTRAINT [DF_module_summary_programming] DEFAULT (0),
  [warranty] [real] NULL CONSTRAINT [DF_module_summary_warranty] DEFAULT (0),
  [design] [real] NULL CONSTRAINT [DF_module_summary_design] DEFAULT (0),
  [supervision] [real] NULL CONSTRAINT [DF_module_summary_supervision] DEFAULT (0),
  [testing] [real] NULL CONSTRAINT [DF_module_summary_testing] DEFAULT (0),
  [A_hrs] [real] NULL CONSTRAINT [DF_module_summary_A_hrs] DEFAULT (0),
  [B_hrs] [real] NULL CONSTRAINT [DF_module_summary_B_hrs] DEFAULT (0),
  [D_hrs] [real] NULL CONSTRAINT [DF_module_summary_D_hrs] DEFAULT (0),
  [E_hrs] [real] NULL CONSTRAINT [DF_module_summary_E_hrs] DEFAULT (0),
  [L_hrs] [real] NULL CONSTRAINT [DF_module_summary_L_hrs] DEFAULT (0),
  [P_hrs] [real] NULL CONSTRAINT [DF_module_summary_P_hrs] DEFAULT (0),
  [S_hrs] [real] NULL CONSTRAINT [DF_module_summary_S_hrs] DEFAULT (0),
  [W_hrs] [real] NULL CONSTRAINT [DF_module_summary_W_hrs] DEFAULT (0),
  [total_hours] [real] NULL CONSTRAINT [DF_module_summary_total_hours] DEFAULT (0),
  [labour_cost] [money] NULL CONSTRAINT [DF_module_summary_labour_cost] DEFAULT (0),
  [material_cost] [money] NULL CONSTRAINT [DF_module_summary_material_cost] DEFAULT (0),
  [part_sundry] [money] NULL CONSTRAINT [DF_module_summary_part_sundry] DEFAULT (0),
  [ign_A] [bit] NOT NULL CONSTRAINT [DF_module_summary_ign_A] DEFAULT (0),
  [ign_B] [bit] NOT NULL CONSTRAINT [DF_module_summary_ign_B] DEFAULT (0),
  [ign_D] [bit] NOT NULL CONSTRAINT [DF_module_summary_ign_D] DEFAULT (0),
  [ign_E] [bit] NOT NULL CONSTRAINT [DF_module_summary_ign_E] DEFAULT (0),
  [ign_L] [bit] NOT NULL CONSTRAINT [DF_module_summary_ign_L] DEFAULT (0),
  [ign_P] [bit] NOT NULL CONSTRAINT [DF_module_summary_ign_P] DEFAULT (0),
  [ign_S] [bit] NOT NULL CONSTRAINT [DF_module_summary_ign_S] DEFAULT (0),
  [ign_W] [bit] NOT NULL CONSTRAINT [DF_module_summary_ign_W] DEFAULT (0),
  [protected] [bit] NOT NULL CONSTRAINT [DF_module_summary_protected] DEFAULT (0),
  [archive?] [bit] NOT NULL CONSTRAINT [DF_module_summary_archive?] DEFAULT (0),
  CONSTRAINT [PK_module_name] PRIMARY KEY CLUSTERED ([module_name])
)
ON [PRIMARY]
GO